"""again

Revision ID: 111b380c3da4
Revises: a5bcdbfbe150
Create Date: 2023-07-11 21:49:00.840754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111b380c3da4'
down_revision = 'a5bcdbfbe150'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospassign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hosp_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospassign')
    # ### end Alembic commands ###
