"""initial

Revision ID: 76e277bb41ca
Revises: 32a384b158bb
Create Date: 2023-10-19 14:16:16.550678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e277bb41ca'
down_revision = '32a384b158bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysistable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_choice', sa.Integer(), nullable=True),
    sa.Column('second_choice', sa.Integer(), nullable=True),
    sa.Column('alloc_hosp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alloc_hosp'], ['hosp.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_choice'], ['hosp.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_choice'], ['hosp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysistable')
    # ### end Alembic commands ###
