"""Updated user table with first, second choice

Revision ID: a5bcdbfbe150
Revises: 3c19dd701dac
Create Date: 2023-04-03 10:53:22.182543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5bcdbfbe150'
down_revision = '3c19dd701dac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_choice', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('second_choice', sa.Integer(), nullable=True))
    op.drop_constraint('users_choice_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'hosp', ['second_choice'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'hosp', ['first_choice'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'choice')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('choice', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_choice_fkey', 'users', 'hosp', ['choice'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'second_choice')
    op.drop_column('users', 'first_choice')
    # ### end Alembic commands ###
