"""'new_db'

Revision ID: bfe535815a7f
Revises: 0b00b7a65731
Create Date: 2023-10-16 10:54:49.036601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe535815a7f'
down_revision = '0b00b7a65731'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('county_name', sa.String(), nullable=False),
    sa.Column('county_num', sa.Integer(), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospassign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hosp_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_num', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_choice', sa.Integer(), nullable=True),
    sa.Column('second_choice', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('posted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['first_choice'], ['hosp.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_choice'], ['hosp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('hospassign')
    op.drop_table('hosp')
    # ### end Alembic commands ###
