"""'serial_numbers_and_qrcode_2'

Revision ID: cdb7a3a6fb77
Revises: 
Create Date: 2023-12-26 19:11:36.003389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb7a3a6fb77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('county_name', sa.String(), nullable=False),
    sa.Column('county_num', sa.Integer(), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospassign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hosp_name', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('qrcode', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('analysistable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_choice', sa.Integer(), nullable=True),
    sa.Column('second_choice', sa.Integer(), nullable=True),
    sa.Column('alloc_hosp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alloc_hosp'], ['hosp.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['first_choice'], ['hosp.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_choice'], ['hosp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_num', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_choice', sa.Integer(), nullable=True),
    sa.Column('second_choice', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('posted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['first_choice'], ['hosp.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['second_choice'], ['hosp.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('analysistable')
    op.drop_table('hospassign')
    op.drop_table('hosp')
    # ### end Alembic commands ###
