"""auto gen hosp table

Revision ID: d8bccb1664c0
Revises: e0265deb785d
Create Date: 2023-02-24 15:26:45.603891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8bccb1664c0'
down_revision = 'e0265deb785d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('county_num', sa.Integer(), nullable=False),
    sa.Column('slots', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('choice', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'hosp', ['choice'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'choice')
    op.drop_table('hosp')
    # ### end Alembic commands ###
